### ISSUE TITLE
V-Ray5 full support with 3ds Max

### ISSUE THREAD

**Issue by pierre-augeard-nfinite** [Azure/batch-extension-templates#81]
Hello,

With the new windows image 1.5.0, V-Ray 5 is the default vray renderer.
This comes with a set of necessary modifications that has not been fully operated.

## 1. 3ds Max renderer name

In 3ds Max the renderer name is not V_Ray_Adv* nor V_Ray_Next* but V_Ray_5

```
print RendererClass.classes
> Default_Scanline_Renderer
> VUE_File_Renderer
> Quicksilver_Hardware_Renderer
> A360_Cloud_Rendering
> V_Ray_GPU_5__hotfix_2
> V_Ray_5__hotfix_2
> ART_Renderer
> Arnold
```

So each maxscript file or script dumping maxscript code (`3dsmax.ps1`) should be modified accordingly.

## 2. `vrayRenderer` template parameter

The `vrayRenderer` parameter in the templates (pool & job) should only accept something like VRay5 instead of either VRayRT or VRayAdv
The file `azure\batch-extension-templates-pipoun\templates\3dsmax\scripts\3dsmax.ps1` should be modified accordingly.

## 3. `PrepareVrayServices.bat`

The file `azure\batch-extension-templates-pipoun\templates\3dsmax\scripts\PrepareVrayServices.bat` has not been updated, it does neither support max2021 nor VRay5

**Comment by davidkydd** [comment]
Thanks Pierre - PR here: https://github.com/Azure/batch-extension-templates/pull/82

**Comment by matthew-rollitt** [comment]
Thanks @pierre-augeard-nfinite for the feedback! 
Let us know if you have any more issues.
